name: bpay
networks:
    bpay_network:
        driver: bridge
services:
    app:
        image: bpay_image
        container_name: bpay_php-fpm
        working_dir: /var/www
        build:
            context: docker/php
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - bpay_network
    nginx:
        image: nginx:alpine
        container_name: bpay_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - bpay_network
    db:
        image: mysql
        restart: unless-stopped
        container_name: bpay_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - ./docker/volumes/db:/var/lib/mysql
        networks:
            - bpay_network
    task:
        image: bpay_image
        container_name: bpay_schedule
        working_dir: /var/www
        volumes:
            - ./:/var/www
        command: [ "php", "/var/www/artisan", "schedule:work" ]
        restart: on-failure
        environment:
            PHP_FPM_POOL_NAME: "my-app_task"
